services:
  iris:
    container_name: iris
    # build:
    #   context: ./iris
    #   dockerfile: Dockerfile
     # target: final
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 1972:1972
      - 52773:52773
      - 53773
    volumes:
      - ./iris:/home/irisowner/dev
    image: genai-workshop-ready2025-iris:latest
  
  

